typography_spectrum: 0.5239370919298381
content_rating:
  adult: false
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.8602229030802846
  lightness: 0.8407642615493387
  saturation: 0.4341133991256356
  rhythmicContrast: 0.7730298675596714
github: true
opengraph:
  image: null
  type: 'https://www.facebook.com/HealingHands.ee/'
  appId: 'https://www.facebook.com/HealingHands.ee/'
layout_spectrum: 0.5896924801636487
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Alice Luukas
  email: aliceluukas@gmail.com
  url: 'http://healinghands.ee'
name: 'HealingHands.ee '
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Healing Hands
content: []
description: Can you imagine what kind of Magic are Hands capable of doing?
purpose:
  - type: contact
    url: 'tel:+372 5349 2723'
    label: Call +372 5349 2723
  - type: external
    url: 'http://thegrid.ai/tervendamine/'
    label: Eesti keel
