name: Alice
favicon: null
layout_spectrum: 0.5896924801636487
typography_spectrum: 0.5239370919298381
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.8602229030802846
  lightness: 0.8407642615493387
  saturation: 0.4341133991256356
  rhythmicContrast: 0.7730298675596714
purpose: []
